### ISSUE TITLE
WeChat SDK

### ISSUE THREAD

**Issue by rhenz** [LawrenceHan/PayWayWeChat#1]
Hi bro. I'm having a problem with implementing WeChat SDK, I'm using the chinese version SDK. I'm trying to present the authentication using `WXApi.sendAuthReq`. When my app opens the wechat, an error alert appears stating that "Login via WeChat failed. The app's universal link failed verification. Unable to log in via WeChat". I hope you have any idea regarding this problem. Than you :)

**Comment by LawrenceHan** [comment]
Send me your problem or screenshot to my email: yangfei6565@163.com
